"""create_users_table

<<<<<<< HEAD:practice-for-week-19-python-project-skeleton-main/migrations/versions/1a03b4e08e70_.py
Revision ID: 1a03b4e08e70
Revises: 
Create Date: 2023-06-30 18:54:41.483270
=======
Revision ID: ffdc0a98111c
Revises:
Create Date: 2020-11-20 15:06:02.230689
>>>>>>> main:practice-for-week-19-python-project-skeleton-main/migrations/versions/20201120_150602_create_users_table.py

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
<<<<<<< HEAD:practice-for-week-19-python-project-skeleton-main/migrations/versions/1a03b4e08e70_.py
revision = '1a03b4e08e70'
=======
revision = 'ffdc0a98111c'
>>>>>>> main:practice-for-week-19-python-project-skeleton-main/migrations/versions/20201120_150602_create_users_table.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('cover_photo', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
<<<<<<< HEAD:practice-for-week-19-python-project-skeleton-main/migrations/versions/1a03b4e08e70_.py
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=True),
    sa.Column('uploaded_on', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
=======

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###qqqqqqqqq
>>>>>>> main:practice-for-week-19-python-project-skeleton-main/migrations/versions/20201120_150602_create_users_table.py


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD:practice-for-week-19-python-project-skeleton-main/migrations/versions/1a03b4e08e70_.py
    op.drop_table('comments')
    op.drop_table('images')
=======
>>>>>>> main:practice-for-week-19-python-project-skeleton-main/migrations/versions/20201120_150602_create_users_table.py
    op.drop_table('users')
    # ### end Alembic commands ###