"""empty message

Revision ID: 8165938c8a10
Revises: b5bdbbaeb7a0
Create Date: 2023-07-07 09:35:38.149528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8165938c8a10'
down_revision = 'b5bdbbaeb7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'image_id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('showcase', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hometown', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=75), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pinterest', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tumblr', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tumblr')
        batch_op.drop_column('pinterest')
        batch_op.drop_column('instagram')
        batch_op.drop_column('twitter')
        batch_op.drop_column('facebook')
        batch_op.drop_column('website')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('hometown')
        batch_op.drop_column('occupation')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('showcase')

    op.drop_table('user_favorites')
    # ### end Alembic commands ###
